CREATE TABLE score (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(24) NOT NULL,
    points           INTEGER NOT NULL,
    wave             INTEGER NOT NULL,
    duration_seconds INTEGER NOT NULL,
    submitted_at     TIMESTAMP WITH TIME ZONE
);

-- Matches the top-N leaderboard query: ORDER BY points DESC, duration_seconds ASC.
CREATE INDEX idx_score_points_duration ON score (points DESC, duration_seconds ASC);
